#Problem 1

Q1.

In [2]:
import numpy as np

arr_empty = np.empty((2,2))
arr_empty

array([[5.19224862e-316, 0.00000000e+000],
       [2.12199579e-314, 5.30886346e+180]])

Q2.

In [3]:
ones_arr = np.ones((4,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Q3.

In [4]:
full_array = np.full((3,3), 7)
full_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Q4.

In [5]:
given = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(given)
zeros_like_arr

array([[0, 0, 0],
       [0, 0, 0]])

Q5.

In [6]:
ones_like_arr = np.ones_like(given)
ones_like_arr

array([[1, 1, 1],
       [1, 1, 1]])

Q6.

In [7]:
new_list = [1,2,3,4]
np_array = np.array(new_list)
np_array

array([1, 2, 3, 4])

#Problem 2

Q1.

In [8]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Q2.

In [9]:
mat_3x3 = np.arange(9).reshape(3,3)
mat_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q3.

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q4.

In [11]:
rand_arr = np.random.random(30)
rand_arr.mean()

np.float64(0.46925851891885245)

Q5.

In [12]:
rand_10 = np.random.random((10,10))
rand_10.min(), rand_10.max()

(np.float64(0.006592622419918204), np.float64(0.9826893705595708))

Q6.

In [14]:
z = np.zeros(10)
z[4] =1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Q7.

In [15]:
arr = np.array([1,2,0,0,4,0])
arr[::-1]

array([0, 4, 0, 0, 2, 1])

Q8.

In [17]:
m = np.ones((5,5))
m[1:-1,1:-1]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Q9.

In [18]:
m = np.ones((5,5))
m[1:-1,1:-1]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#Problem 3

In [21]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

Q1.

In [22]:
x + y

array([[ 6,  8],
       [10, 13]])

Q2.

In [23]:
x - y

array([[-4, -4],
       [-4, -3]])

Q3.

In [24]:
x * y

array([[ 5, 12],
       [21, 40]])

Q4.

In [25]:
x**2

array([[ 1,  4],
       [ 9, 25]])

Q5.

In [28]:
np.dot(v,w)
np.dot(x,v)
np.dot(x,y)

array([[19, 22],
       [50, 58]])

In [29]:
np.vstack((x,y))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [30]:
np.column_stack((v,w))

array([[ 9, 11],
       [10, 12]])

Q7.

In [31]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

x is 2×2 (2D). v is 1D (size 2). They cannot be concatenated because their dimensions do not match (2D vs 1D).

#Problem 4

In [32]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Q1.

In [33]:
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

Q2.

In [35]:
AB = np.dot(A,B)
BA = np.dot(B,A)
AB,BA

(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]))

Q3.

In [36]:
AB = np.dot(A,B)
lhs = AB.T
rhs = np.dot(B.T, A.T)
lhs,rhs

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

#Matrix form AX = B

In [38]:

A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

In [40]:
X = np.dot(np.linalg.inv(A),B)
X

array([ 2.,  1., -2.])

In [41]:
np.linalg.solve(A,B)

array([ 2.,  1., -2.])

In [43]:
import time
import numpy as np

size = 1_000_000

# Python list
a = list(range(size))
b = list(range(size))

start = time.time()
c = [a[i] + b[i] for i in range(size)]
end = time.time()

print("List addition time:", end-start)

# NumPy
a_np = np.arange(size)
b_np = np.arange(size)

start = time.time()
c_np = a_np + b_np
end = time.time()

print("NumPy addition time:",end-start)


List addition time: 0.11327052116394043
NumPy addition time: 0.004412651062011719


In [45]:
# Python list
start = time.time()
c = [a[i] * b[i] for i in range(size)]
end = time.time()
print("List multiplication time:", end-start)

# NumPy
start = time.time()
c_np = a_np * b_np
end = time.time()
print("NumPy multiplication time:",end-start)

List multiplication time: 0.23902249336242676
NumPy multiplication time: 0.005139350891113281


In [48]:
# Python
start = time.time()
dot_list = sum(a[i] * b[i] for i in range(size))
end = time.time()
print("List dot time:", end-start)

# NumPy
start = time.time()
dot_np = np.dot(a_np, b_np)
end = time.time()
print("NumPy dot time:",end-start)

List dot time: 0.205275297164917
NumPy dot time: 0.0022308826446533203


In [ ]:
# Python lists
import random
M1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
M2 = [[random.random() for _ in range(1000)] for _ in range(1000)]

start = time.time()
result = [[sum(a*b for a,b in zip(r,c)) for c in zip(*M2)] for r in M1]
end = time.time()
print("List matrix multiplication time:",end-start)

In [ ]:
# NumPy
M1_np = np.random.random((1000,1000))
M2_np = np.random.random((1000,1000))

start = time.time()
result_np = np.dot(M1_np, M2_np)
end = time.time()
print("NumPy matrix multiplication time:",end-start)